services:
  meilisearch:
    image: getmeili/meilisearch:prototype-japanese-13
    container_name: meilisearch
    ports:
      - "7700:7700"
    volumes:
      - ./meili_data:/meili_data # ← ここが重要！
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH_PSW}
      - MEILI_DB_PATH=/meili_data
    restart: always

  api:
    build: ./api
    container_name: pdf-search-api
    ports:
      - "3000:3000"
    environment:
      - MEILISEARCH_HOST=http://meilisearch:7700
      - MEILISEARCH_PSW=${MEILISEARCH_PSW}
      - PORT=3000
    depends_on:
      - meilisearch
    restart: always

  file_server:
    image: nginx:alpine
    container_name: file-server
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./file_data:/data:ro
    restart: always

  frontend:
    build: ./frontend
    container_name: pdf-search-frontend
    ports:
      - "8081:8080"
    environment:
      - API_URL=http://api:3000
      - PORT=8080
    depends_on:
      - api
    restart: always
